### ISSUE TITLE
Create Member Card Component

### ISSUE THREAD

**Issue by ahmadadnan16** [ahmadadnan16/upds-clone#5]
Hey @jayashri1998,

create card component as visible on the below link , the data should be dynamic. First create component and then loop it in desired page.

https://www.udpsalumni.org/members.dz

Feel free to reach 😊

Thanks.

**Comment by ahmadadnan16** [comment]
Also try to add information of page as seen in the members page.🙂

**Comment by jayashri1998** [comment]
Ok.. I will go through assign ticket... if   I got any issues i might get back to you...

**Comment by ahmadadnan16** [comment]
Hey @jayashri1998 ,

I expect to complete the task by EOD.😊

**Comment by jayashri1998** [comment]
ok ..

**Comment by ahmadadnan16** [comment]
https://shadbox-test11.onrender.com/api/v1/members


Fetch the data for member from here

**Comment by ahmadadnan16** [comment]
issue closed 😍
